### PR TITLE
Update public pool names

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by alexperovich** [comment]
Well, the build tried to start in the right project this time at least https://dev.azure.com/dnceng-public/public/_build/results?buildId=3362&view=results

Can you tell me what that service connection is supposed to be?

**Comment by dougbu** [comment]
> Can you tell me what that service connection is supposed to be?

Could you check the equivalent dnceng/public pipeline❔ I'm not sure where to look.

**Comment by alexperovich** [comment]
okay, this looks to be fixed. I had to use the oauth connection, but it is doing the right things.

**Pull request merged**
